"""new_tables

Revision ID: cf8d05772b9f
Revises: 953e0f676da9
Create Date: 2021-06-13 19:05:37.531888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8d05772b9f'
down_revision = '953e0f676da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('clg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clg_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
