"""created blueprints

Revision ID: 546cf1124ce1
Revises: 
Create Date: 2021-06-13 22:48:00.089076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546cf1124ce1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('clg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clg_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('colleges')
    # ### end Alembic commands ###
